Importing dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm

data collection and analysis

In [2]:
#loading the dataset 
data = pd.read_csv("/content/diabetes.csv")

In [3]:
data.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [4]:
data.shape

(768, 9)

In [5]:
#statistical measures of data
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [6]:
#getting count of output with value_counts() funtion
data["Outcome"].value_counts()

0    500
1    268
Name: Outcome, dtype: int64

In [7]:
# seperating values
X = data.drop(columns = "Outcome", axis = 1) #axis 0 is row and axis 1 is column
Y = data["Outcome"]

Data standardization

In [8]:
scaler = StandardScaler()

In [9]:
standardized_data = scaler.fit_transform(X)   #standardizing data for training and storing it in a variable

In [10]:
X = standardized_data
Y = Y = data["Outcome"]

Train test data spliting

In [11]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size = 0.2, stratify = Y, random_state = 2)

In [12]:
print(X.shape, X_train.shape, X_test.shape)
print(Y.shape, Y_train.shape, Y_test.shape)

(768, 8) (614, 8) (154, 8)
(768,) (614,) (154,)

Actual Training

In [13]:
classifier = svm.SVC(kernel='linear')
classifier.fit(X_train, Y_train)

SVC(kernel='linear')

Model Evaluation

In [14]:
#training data's accuracy score 
X_train_prediction = classifier.predict(X_train) 
X_train_accuracy = accuracy_score(X_train_prediction, Y_train)

print("Accuracy score is :", X_train_accuracy)

Accuracy score is : 0.7866449511400652

In [15]:
#testing data's accuracy score
X_test_prediction = classifier.predict(X_test) 
X_test_accuracy = accuracy_score(X_test_prediction, Y_test)

print("Accuracy score is :", X_test_accuracy)

Accuracy score is : 0.7727272727272727

Making predictive system

In [19]:
#id --> input data
#na --> numpy array
#re --> reshaped
#std -->  standardized

id = (1,89,66,23,94,28.1,0.167,21)
na_id = np.asarray(id)
re_na_id = na_id.reshape(1,-1)
std_na_id =  scaler.transform(re_na_id)

prediction = classifier.predict(std_na_id)
print(std_na_id)
print(prediction)

if prediction == 0:
  print("The patient is Non_diabetic")
else:
  print("The patient is Diabetic")

[[-0.84488505 -0.99820778 -0.16054575  0.15453319  0.12330164 -0.49404308
  -0.92076261 -1.04154944]]
[0]
The patient is Non_diabetic

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"